// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwdnsfukootxidbofgnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53ZG5zZnVrb290eGlkYm9mZ25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MTExMDIsImV4cCI6MjA3NjM4NzEwMn0.7lNfjt8CYfmnySWZOL9AcFn-4Yu-0rZfqHoF_pdvpxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});